Document: librutil2
Title: Debian librutil2 Manual
Author: <insert document author here>
Abstract: This manual describes what librutil2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/librutil2/librutil2.sgml.gz

Format: postscript
Files: /usr/share/doc/librutil2/librutil2.ps.gz

Format: text
Files: /usr/share/doc/librutil2/librutil2.text.gz

Format: HTML
Index: /usr/share/doc/librutil2/html/index.html
Files: /usr/share/doc/librutil2/html/*.html
